vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: true
        cache: file
#        type: annotation    # or attribute
        type: attribute
    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            directory_namer: pasaia.vich.directory.namer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
