vich_uploader:
    db_driver: orm

    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'

            #            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: pasaia.vich.directory.namer
            #            directory_namer:
            #                service: vich_uploader.namer_directory_property
            #                options: { property: 'name', transliterate: true } # supposing that the object contains a "slug" attribute or a "getSlug" method

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
