FROM nginx:1.21-alpine

#ADD ./docker/nginx/conf/default.conf /etc/nginx/conf.d/default.conf
#ADD ./docker/nginx/conf/nginx.conf /etc/nginx/default.conf

COPY public /usr/src/app/public

EXPOSE 80
EXPOSE 443
