# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $projectDir: "%kernel.project_dir%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    pasaia.vich.directory.namer:
        class: App\Utils\VichDirectoryNamer
        arguments: ['%kernel.project_dir%', 'kontratuid']
        public: true

    Redis:
        # también puedes usar las clases \RedisArray, \RedisCluster o \Predis\Client
        class: Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(int:REDIS_PORT)%'
            # Si tu servidor Redis requiere una contraseña, elimine el comentario de las siguientes líneas:
            # - auth:
            #     - '%env(REDIS_PASSWORD)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    App\Security\PasaiaLdapService:
        class: App\Security\PasaiaLdapService
        autoconfigure: true
        arguments:
            - "%env(resolve:LDAP_IP)%"
            - "%env(resolve:LDAP_SEARCH_DN)%"
            - "%env(resolve:LDAP_BASE_DN)%"
            - "%env(resolve:LDAP_PASSWD)%"
            - "%env(resolve:LDAP_ADMIN_TALDEAK)%"
            - "%env(resolve:LDAP_KUDEATU_TALDEAK)%"
            - "%env(resolve:LDAP_USER_TALDEA)%"
            - '@Doctrine\ORM\EntityManagerInterface'
